FullstackOpdracht/Controllers/HotelController.cs
using SerpApi;
using System.Collections;
using FullstackOpdracht.Domains.Entities;
using FullstackOpdracht.Services.Interfaces;
using FullstackOpdracht.Services;
using Newtonsoft.Json.Linq;
using Microsoft.AspNetCore.Mvc;
using FullstackOpdracht.ViewModels;
using Hotel = FullstackOpdracht.ViewModels.Hotel;

namespace FullstackOpdracht.Controllers
{
    public class HotelController : Controller
    {
        private readonly ExtendedMatchService _matchService;
        private readonly IService<Stadium> _stadiumService;

        public HotelController(ExtendedMatchService matchService, IService<Stadium> stadiumService)
        {
            _matchService = matchService;
            _stadiumService = stadiumService;
        }

        public async Task<IActionResult> Index(HotelVM hotel)
        {
            return View(hotel);
        }

        //call
        public async Task<IActionResult> Hotel(int? id)
        {
            try
            {
                Match match = await _matchService.FindById(Convert.ToInt32(id));
                Stadium stadium = await _stadiumService.FindById(Convert.ToInt32(match.HomeTeam.StadiumId));

                string apiKey = "0df718e73eaae1d68a6cf50a4cfd90025e0c6d1ffb7511196a8a29465079df52";
                Hashtable ht = new Hashtable();
                ht.Add("engine", "google_hotels");
                ht.Add("q", stadium.City);
                ht.Add("check_in_date", DateTime.Now.ToString("yyyy-MM-dd"));
                ht.Add("check_out_date", DateTime.Now.AddDays(1).ToString("yyyy-MM-dd"));
                ht.Add("gl", "be");
                ht.Add("hl", "nl");
                ht.Add("currency", "EUR");

                GoogleSearch search = new GoogleSearch(ht, apiKey);
                JObject data = search.GetJson();

                JArray properties = (JArray)data["properties"];
                var hotels = properties.Take(3).Select(hotel => new Hotel
                {
                    Name = hotel["name"]?.ToString() ?? "Unknown",
                    OverallRating = hotel["overall_rating"]?.ToObject<double>() ?? 0,
                    Price = hotel["rate_per_night"]?["lowest"]?.ToString() ?? "Unknown",
                    Image = hotel["images"]?.First?["thumbnail"]?.ToString() ?? "Unknown",
                    URL = hotel["link"]?.ToString() ?? "Unknown",
                }).ToList();

                var hotelViewModel = new HotelVM { Hotels = hotels };

                return View("Index", hotelViewModel);
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Error retrieving hotel information: {ex.Message}");
            }
        }
    }
}

FullstackOpdracht/Controllers/ProfligaController.cs
using AutoMapper;
using FullstackOpdracht.Domains.Entities;
using FullstackOpdracht.Services;
using FullstackOpdracht.Services.Interfaces;
using FullstackOpdracht.ViewModels;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FullstackOpdracht.Controllers
{
    public class ProfligaController : Controller
    {
        private readonly ExtendedMatchService _matchExService;
        private readonly IService<Team> _teamService;
        private readonly IMapper _mapper;
        private readonly ExtendedSectionService _sectionService;

        public ProfligaController(IMapper mapper, ExtendedMatchService matchEx, IService<Team> teamservice, ExtendedSectionService sectionService)
        {
            _mapper = mapper;
            _matchExService = matchEx;
            _teamService = teamservice;
            _sectionService = sectionService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Voorstelling()
        {
            return View();
        }

        // toont kalender met alle matches
        public async Task<IActionResult> Kalender()
        {
            ViewBag.lstPloegen = new SelectList(await _teamService.GetAll(), "Id", "Name");

            try
            {
                var matchList = await _matchExService.GetAll();

                List<MatchVM> matchVMs = new List<MatchVM>();

                if (matchList != null)
                {
                    //sorteren
                    matchList = matchList.OrderByDescending(m => m.MatchDate).ToList();
                    matchVMs = _mapper.Map<List<MatchVM>>(matchList);
                }
                return View(matchVMs);
            }
            catch (Exception ex)
            {
                throw;
            }

        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Matches(int teamId)
        {
            try
            {
                var matches = await _matchExService.GetMatchesForTeam(teamId);
                //sorteren
                matches = matches.OrderByDescending(m => m.MatchDate).ToList();

                var data = _mapper.Map<List<MatchVM>>(matches);
                return View(data);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        //zie alle matches van de komende maand, klik op bestellen en ga dan naar "createTicket"
        public async Task<IActionResult> Tickets()
        {
            try
            {
                var matchlst = await _matchExService.GetTicketMatches();
                List<MatchVM> matchVMs = new List<MatchVM>();
                if (matchlst != null)
                {
                    //sorteren
                    matchlst = matchlst.OrderBy(m => m.MatchDate).ToList();
                    matchVMs = _mapper.Map<List<MatchVM>>(matchlst);
                }
                return View(matchVMs);
            }
            catch (Exception ex)
            {
                Console.WriteLine("error in controlller");
                return View("Index");
            }
        }

        

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SetAppLanguage(string lang, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(
                    new RequestCulture(lang)),
                    new CookieOptions
                    {
                        Expires = DateTimeOffset.UtcNow.AddYears(1)
                    }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

FullstackOpdracht/Controllers/ShoppingCartController.cs
using AutoMapper;
using FullstackOpdracht.Domains.Data;
using FullstackOpdracht.Domains.Entities;
using FullstackOpdracht.Extensions;
using FullstackOpdracht.Services;
using FullstackOpdracht.Services.Interfaces;
using FullstackOpdracht.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using FullstackOpdracht.Util.Interfaces;
using FullstackOpdracht.Util.PDF.Interfaces;
using Newtonsoft.Json.Linq;
using System.Collections;
using SerpApi;
using FullstackOpdracht.Areas.Data;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using System.Threading;


namespace FullstackOpdracht.Controllers
{
    public class ShoppingCartController : Controller
    {
        private IEmailSend _emailSend;
        private ICreatePDF _createPDF;
        private readonly ExtendedTicketService _ticketService;
        private readonly ExtendedMembershipService _membershipService;
        private readonly ExtendedMatchService _matchService;
        private readonly ExtendedSectionService _sectionService;
        private readonly ExtendedSeatService _seatService;
        private readonly RingService _ringService;
        private readonly ExtendedBookingTicketService _bookingTicketService;
        private readonly ExtendedBookingService _bookingService;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IService<Stadium> _stadiumService;
        private readonly Microsoft.AspNetCore.Identity.UserManager<ApplicationUser> _userManager;
        private readonly ExtendedUserService _userService;
        private readonly IService<BookingMembership> _bookingMembershipService;
        private readonly IService<Team> _teamService;
        private readonly IMapper _mapper;

        public ShoppingCartController(ExtendedSeatService seatService, ExtendedTicketService ticketService,
            ExtendedMembershipService membershipService, IMapper mapper,
            ExtendedMatchService matchService, ExtendedSectionService sectionService, RingService ringService,
            ExtendedBookingService bookingService, IEmailSend emailSend, IWebHostEnvironment hostingEnvironment,
            ICreatePDF createPDF, IService<Stadium> stadiumservice, Microsoft.AspNetCore.Identity.UserManager<ApplicationUser> userManager,
            ExtendedUserService userService, ExtendedBookingTicketService bookingTicketService, IService<BookingMembership> bookingMembership)
        {
            _ticketService = ticketService;
            _membershipService = membershipService;
            _mapper = mapper;
            _matchService = matchService;
            _sectionService = sectionService;
            _ringService = ringService;
            _mapper = mapper;
            _seatService = seatService;
            _bookingService = bookingService;
            _emailSend = emailSend;
            _hostingEnvironment = hostingEnvironment;
            _createPDF = createPDF;
            _stadiumService = stadiumservice;
            _userManager = userManager;
            _userService = userService;
            _bookingTicketService = bookingTicketService;
            _bookingMembershipService = bookingMembership;
        }

        [Authorize]
        public IActionResult Index()
        {
            ShoppingCartVM? cartList =
                HttpContext.Session.GetObject<ShoppingCartVM>("ShoppingCart");
            return View(cartList);
        }

        public async Task<IActionResult> CreateTicket(int? id)
        {
            // Retrieve the match with the given id
            Match match = await _matchService.FindById(Convert.ToInt32(id));

            // Retrieve the sections/ rings for the match
            IEnumerable<Section> sections = await _sectionService.GetSectionsByStadium(Convert.ToInt32(match.HomeTeam.StadiumId));
            IEnumerable<Ring> rings = await _ringService.GetRingsByStadium(Convert.ToInt32(match.HomeTeam.StadiumId));

            if (match != null && sections != null && rings != null)
            {
                CreateTicketVM model = new CreateTicketVM
                {
                    matchID = id,
                    Name = match.HomeTeam.Name + " vs " + match.AwayTeam.Name,
                    Sections = sections.Select(s => new SelectListItem { Value = s.Id.ToString(), Text = s.Name }).ToList(), // Sections ophalen van de stadium based op match, home team
                    Rings = rings.Select(r => new SelectListItem { Value = r.Id.ToString(), Text = r.Name }).ToList()// Rings ophalen van de stadium based op match, home team
                };
                return View(model);
            }
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTicket(CreateTicketVM ticketVM, int? matchID)
        {
            if (ticketVM == null)
            {
                return NotFound();
            }

            Match? match = await _matchService.FindById(Convert.ToInt32(matchID));
            Ring? ring = await _ringService.FindById(Convert.ToInt32(ticketVM.Ring));
            Section? section = await _sectionService.FindById(Convert.ToInt32(ticketVM.Section));

            int price = GetPriceForMatch(ring, section);

            ShoppingCartVM shopping;
            if (HttpContext.Session.GetObject<ShoppingCartVM>("ShoppingCart") != null)
            {
                shopping = HttpContext.Session.GetObject<ShoppingCartVM>("ShoppingCart");
            }
            else
            {
                shopping = new ShoppingCartVM();
                shopping.Cart = new List<CartVM>();
            }

            DateTime newMatchDate = match.MatchDate;
            
            bool hasMatchOnSameDay = shopping.Cart.Any(ticket => ticket.DateCreated.Day == newMatchDate.Day);
            IEnumerable<Ticket> ticketsOfUser = await _ticketService.GetAllTicketsByUserIdAsync(User.FindFirstValue(ClaimTypes.NameIdentifier));
            bool hasTicketFromSameDay = ticketsOfUser.Any(t => t.Match.MatchDate.Day == newMatchDate.Day);



            if (match != null && !hasMatchOnSameDay && !hasTicketFromSameDay)
            {
                string matchName = match.HomeTeam.Name + " vs " + match.AwayTeam.Name;

                CartVM item = new CartVM
                {
                    Naam = matchName,
                    Aantal = 1,
                    Prijs = price,
                    MatchId = match.Id,
                    Section = section, // zullen mogelijk geven om dit aan te passen
                    Ring = ring, // zullen mogelijk geven om dit aan te passen
                    DateCreated = match.MatchDate, // datum van match voor controle, geen nut om datum bij te houden van creatie ticket
                };
                
                shopping?.Cart?.Add(item);
                HttpContext.Session.SetObject("ShoppingCart", shopping);
            } else
            {
                return RedirectToAction("DuplicateTicket");
            }
            
            return RedirectToAction("Index", "ShoppingCart");
        }

        public IActionResult DuplicateTicket()
        {
            return View("DuplicateTicket");
        }

        public async Task<IActionResult> GetSections(int ringId)
        {
            var sections = await _sectionService.GetSectionsByRing(ringId);
            return Json(sections.Select(s => new { id = s.Id, name = s.Name }));
        }


        public int GetPriceForMatch(Ring ring, Section section)
        {
            float basePrice = 30;
            float ringMultiplier = 1.0f;
            float sectionMultiplier = 1.0f;

           
            // Check the ring name and apply the appropriate multiplier
            if (ring.Name == "BovensteRing")
            {
                ringMultiplier = 1.5f;
            }
            else if (ring.Name == "OndersteRing")
            {
                ringMultiplier = 1.2f;
            }

            // Check the section name and apply the appropriate multiplier
            if (section.Name == "Onderste Ring Thuis" || section.Name == "Onderste Ring Bezoekers")
            {
                sectionMultiplier = 1.3f;
            }
            else if (section.Name == "Onderste Ring Oost" || section.Name == "Onderste Ring West")
            {
                sectionMultiplier = 1.0f;
            }
            // Check the section name and apply the appropriate multiplier
            if (section.Name == "Bovenste Ring Thuis" || section.Name == "Bovenste Ring Bezoekers")
            {
                sectionMultiplier = 1.3f;
            }
            else if (section.Name == "Bovenste Ring Oost" || section.Name == "Bovenste Ring West")
            {
                sectionMultiplier = 1.0f;
            }

            // Calculate the final price
            int finalPrice =  Convert.ToInt32(basePrice * ringMultiplier * sectionMultiplier);

            return finalPrice;
        }

        [HttpPost, ValidateAntiForgeryToken, Authorize]
        public async Task<IActionResult> Checkout(ShoppingCartVM shoppingCart)
        {
            ShoppingCartVM shopping;

            if (HttpContext.Session.GetObject<ShoppingCartVM>("ShoppingCart") != null)
            {
                shopping = HttpContext.Session.GetObject<ShoppingCartVM>("ShoppingCart");
            }
            else
            {
                shopping = new ShoppingCartVM();
                shopping.Cart = new List<CartVM>();
            }

            var mailTickets = new List<Ticket>();
            var mailMatches = new List<Match>();
            var mailSections = new List<string>();

            var mailMemberships = new List<Membership>();
            var mailTeams = new List<string>();
            var membershipSections = new List<string>();
            // Loop through each item in the shopping cart

FullstackOpdracht/Views/ShoppingCart/Checkout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h2>bedankt voor uw bestelling! check uw mail voor uw ticket(s).</h2>

FullstackOpdracht/Views/ShoppingCart/CreateTicket.cshtml
@model FullstackOpdracht.ViewModels.CreateTicketVM

@{
    ViewData["Title"] = "CreateTicket";
}

<h1>Kies locatie</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Select">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" readonly="readonly" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ring" class="control-label"></label>
                <select required asp-for="Ring" class="form-control" asp-items="@Model.Rings" id="ringSelect">
                    <option value="">--Select a ring</option>
                </select>
                <span asp-validation-for="Ring" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Section" class="control-label" ></label>
                <select required asp-for="Section" class="form-control" asp-items="@Model.Sections" id="sectionSelect">
                    <option value="">--Select a section</option>
                </select>
                <span asp-validation-for="Section" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add ticket" class="btn btn-primary" asp-route-matchID="@Model.matchID"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Tickets">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            $('#ringSelect').change(function () {
                var selectedRingId = $(this).val();
                $.ajax({
                    url: '/ShoppingCart/GetSections',
                    type: 'GET',
                    data: { ringId: selectedRingId },
                    success: function (data) {
                        $('#sectionSelect').empty();
                        $.each(data, function (index, value) {
                            $(console.log(value.id + value.name));
                            $('#sectionSelect').append('<option value="' + value.id + '">' + value.name + '</option>');
                        });
                    }
                });
            });
        });
    </script>

}

FullstackOpdracht/Views/ShoppingCart/DuplicateTicket.cshtml
@{
}

<h2>U hebt al een ticket aangekocht voor deze datum.</h2>
<a asp-action="Tickets" asp-controller="Profliga">Klik hier om een ander ticket te bestellen!</a>

FullstackOpdracht/Views/ShoppingCart/Index.cshtml
@model FullstackOpdracht.ViewModels.ShoppingCartVM

@{
    ViewData["Title"] = "Index";
}

<h3>
    Uw winkelkar :
</h3>

@if (Model != null)
{
    @if (Model.Cart.Count > 0)
    {
        <form asp-action="Checkout">
            <table>
                <tr>
                    <th>Hotel</th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cart[0].Naam)
                    </th>
                    <th>
                        Vak
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cart[0].Aantal)
                    </th>
                    <th>
                        @(@Html.DisplayNameFor(model => model.Cart[0].Prijs) + " Per Ticket")
                    </th>
                    <th>
                        Subtotaal
                    </th>
                </tr>
                @{
                    float? total = 0;
                }
                @for (var i = 0; i < Model.Cart.Count; i++)
                {
                    <tr>
                        <td>
                            <a asp-controller="Hotel" asp-action="Hotel" asp-route-id="@Model.Cart[i].MatchId">
                                Hotels in de buurt
                            </a>
                        </td>
                        <td>
                            <p class="custom-name">
                                @Model.Cart[i].Naam
                            </p>
                        </td>
                        <td><section>@Model.Cart[i].Section.Name</section></td>
                        <td>
                            @if (Model.Cart[i].TeamId != null)
                            {
                                <input asp-for="@Model.Cart[i].Aantal" type="number"
                                min="1" max="1" data-aantal=@i />

                            } else
                            {
                                <input asp-for="@Model.Cart[i].Aantal" type="number"
                                       min="1" max="4" data-aantal=@i />
                            }
                        </td>
                        <td>
                            <input asp-for="@Model.Cart[i].Prijs" type="number"
                                   readonly="readonly" />

                            @{
                                var subtotaal = Model.Cart[i].Prijs
                                * Model.Cart[i].Aantal;
                                total += subtotaal;
                            }
                        </td>
                        <td>
                            <input id="@("txtSubTotal" + @i)"
                                   value="@subtotaal"
                                   type="number" readonly="readonly" />
                        </td>

                        <td>
                            <a asp-action="Delete" asp-route-CartId="@Model.Cart[i].CartId">
                                <img class="trash" src="~/images/trashcan.png" />
                            </a>
                        </td>
                    </tr>
                }
                <tr>
                    <td id="cart-total">
                        Total  <input id="txtTotal" value="@total"
                                      type="number" readonly="readonly" />
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="submit" value="Checkout"
                               class="btn btn-default bg-secondary text-white" asp-action="Checkout" />
                    </td>
                </tr>
            </table>
        </form>
    }
    else
    {
        @Html.Raw("Jouw winkelkar is leeg")
    }
}
else
{
    @Html.Raw("Jouw winkelkar is leeg")
}

@section scripts {
    <script>
        $(document).ready(function () {
            // Listen for changes in quantity fields
            $("input[data-aantal]").change(function () {
                // Get the index from the data-aantal attribute
                var index = $(this).data("aantal");

                // Calculate the new subtotal
                var price = parseFloat($(`#Cart_${index}__Prijs`).val());
                var quantity = parseInt($(this).val());
                var subtotal = price * quantity;

                // Update the subtotal field
                $(`#txtSubTotal${index}`).val(subtotal.toFixed(2));

                // Calculate the new total
                var total = 0;
                $("input[id^='txtSubTotal']").each(function () {
                    total += parseFloat($(this).val());
                });

                // Update the total field
                $("#txtTotal").val(total.toFixed(2));
            });
        });
    </script>
}
<a asp-controller="Profliga" asp-action="Tickets"> Ga verder met winkelen</a>

FullstackOpdracht/Views/ShoppingCart/NoSeat.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Er is geen stoel beschikbaar in dit vak, excuses</h2>