FullstackOpdracht/Controllers/ProfligaController.cs
using AutoMapper;
using FullstackOpdracht.Domains.Entities;
using FullstackOpdracht.Services;
using FullstackOpdracht.Services.Interfaces;
using FullstackOpdracht.ViewModels;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FullstackOpdracht.Controllers
{
    public class ProfligaController : Controller
    {
        private readonly ExtendedMatchService _matchExService;
        private readonly IService<Team> _teamService;
        private readonly IMapper _mapper;
        private readonly ExtendedSectionService _sectionService;

        public ProfligaController(IMapper mapper, ExtendedMatchService matchEx, IService<Team> teamservice, ExtendedSectionService sectionService)
        {
            _mapper = mapper;
            _matchExService = matchEx;
            _teamService = teamservice;
            _sectionService = sectionService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Voorstelling()
        {
            return View();
        }

        // toont kalender met alle matches
        public async Task<IActionResult> Kalender()
        {
            ViewBag.lstPloegen = new SelectList(await _teamService.GetAll(), "Id", "Name");

            try
            {
                var matchList = await _matchExService.GetAll();

                List<MatchVM> matchVMs = new List<MatchVM>();

                if (matchList != null)
                {
                    //sorteren
                    matchList = matchList.OrderByDescending(m => m.MatchDate).ToList();
                    matchVMs = _mapper.Map<List<MatchVM>>(matchList);
                }
                return View(matchVMs);
            }
            catch (Exception ex)
            {
                throw;
            }

        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Matches(int teamId)
        {
            try
            {
                var matches = await _matchExService.GetMatchesForTeam(teamId);
                //sorteren
                matches = matches.OrderByDescending(m => m.MatchDate).ToList();

                var data = _mapper.Map<List<MatchVM>>(matches);
                return View(data);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        //zie alle matches van de komende maand, klik op bestellen en ga dan naar "createTicket"
        public async Task<IActionResult> Tickets()
        {
            try
            {
                var matchlst = await _matchExService.GetTicketMatches();
                List<MatchVM> matchVMs = new List<MatchVM>();
                if (matchlst != null)
                {
                    //sorteren
                    matchlst = matchlst.OrderBy(m => m.MatchDate).ToList();
                    matchVMs = _mapper.Map<List<MatchVM>>(matchlst);
                }
                return View(matchVMs);
            }
            catch (Exception ex)
            {
                Console.WriteLine("error in controlller");
                return View("Index");
            }
        }

        

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SetAppLanguage(string lang, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(
                    new RequestCulture(lang)),
                    new CookieOptions
                    {
                        Expires = DateTimeOffset.UtcNow.AddYears(1)
                    }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

FullstackOpdracht/Controllers/StadionController.cs
using AutoMapper;
using FullstackOpdracht.Domains.Entities;
using FullstackOpdracht.Services;
using FullstackOpdracht.Services.Interfaces;
using FullstackOpdracht.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FullstackOpdracht.Controllers
{
    public class StadionController : Controller
    {
        private readonly IService<Stadium> _stadiumService;
        private readonly IMapper _mapper;
        private readonly ExtendedSeatService _seatService;

        public StadionController(IMapper mapper, IService<Stadium> stadium, ExtendedSeatService seatService)
        {
            _mapper = mapper;
            _stadiumService = stadium;
            _seatService = seatService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var listStadion = await _stadiumService.GetAll();
                var stadions = new List<StadiumVM>();
                foreach (var item in listStadion)
                {
                    var seats = await _seatService.GetSeatsByStadium(item.Id);
                    int seatCount = seats.Count;
                    item.TotalSeats = seatCount;


                    StadiumVM stadium = new StadiumVM
                    {
                        Id = item.Id,
                        Name = item.Name,
                        City = item.City,
                        Address = item.Address,
                        TotalSeats = seatCount
                    };
                    stadions.Add(stadium);
                    await _stadiumService.Update(item);
                }
                
                //var data = _mapper.Map<List<StadiumVM>>(listStadion);

                if (stadions != null)
                {
                    return View(stadions);
                }

                return View();
            }
            catch (Exception ex)
            {
                throw new Exception();
            }
            
        }

        [HttpGet]
        public async Task<IActionResult> Information(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                var stadium = await _stadiumService.FindById(id);
                StadiumVM VM = _mapper.Map<StadiumVM>(stadium);
                return View(VM);
            }
            catch
            {
                throw new Exception();
            }
        }
    }
}

FullstackOpdracht/Controllers/SubscriptionController.cs
using AutoMapper;
using FullstackOpdracht.Domains.Entities;
using FullstackOpdracht.Extensions;
using FullstackOpdracht.Services;
using FullstackOpdracht.Services.Interfaces;
using FullstackOpdracht.Services.IService;
using FullstackOpdracht.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace FullstackOpdracht.Controllers
{
    public class SubscriptionController : Controller
    {
        private readonly IService<Team> _teamService;
        private readonly IMapper _mapper;
        private readonly ExtendedSectionService _sectionService;
        private readonly RingService _ringService;
        private readonly ExtendedMembershipService _membershipService;

        public SubscriptionController(IMapper mapper, IService<Team> team, ExtendedSectionService sectionService,
            RingService ringService, ExtendedMembershipService membershipService)
        {
            _mapper = mapper;
            _teamService = team;
            _sectionService = sectionService;
            _ringService = ringService;
            _membershipService = membershipService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var teamList = await _teamService.GetAll();
                List<TeamVM> teamVMs = new List<TeamVM>();
                if (teamList != null)
                {
                    teamVMs = _mapper.Map<List<TeamVM>>(teamList);
                }
                return View(teamVMs);
            }
            catch (Exception ex)
            {
                Console.WriteLine("error in controlller");
                return View("Index", "Profliga");
            }
        }

        public async Task<IActionResult> CreateAbonnement(int? id)
        {
            Team team = await _teamService.FindById(Convert.ToInt32(id));

            // Retrieve the sections/ rings for the match
            IEnumerable<Section> sections = await _sectionService.GetSectionsByStadium(Convert.ToInt32(id));
            IEnumerable<Ring> rings = await _ringService.GetRingsByStadium(Convert.ToInt32(id));

            if (team != null && sections != null && rings != null)
            {
                CreateMembershipVM model = new CreateMembershipVM
                {
                    TeamId = id,
                    Name = team.Name,
                    Sections = sections.Select(s => new SelectListItem { Value = s.Id.ToString(), Text = s.Name }).ToList(), // Sections ophalen van de stadium based op match, home team
                    Rings = rings.Select(r => new SelectListItem { Value = r.Id.ToString(), Text = r.Name }).ToList()// Rings ophalen van de stadium based op match, home team
                };
                return View(model);
            }
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAbonnement(CreateMembershipVM membershipVM, int? teamID)
        {
            if (membershipVM == null)
            {
                return NotFound();
            }

            Team? team = await _teamService.FindById(Convert.ToInt32(teamID));
            Ring? ring = await _ringService.FindById(Convert.ToInt32(membershipVM.Ring));
            Section? section = await _sectionService.FindById(Convert.ToInt32(membershipVM.Section));

            ShoppingCartVM shopping;
            if (HttpContext.Session.GetObject<ShoppingCartVM>("ShoppingCart") != null)
            {
                shopping = HttpContext.Session.GetObject<ShoppingCartVM>("ShoppingCart");
            }
            else
            {
                shopping = new ShoppingCartVM();
                shopping.Cart = new List<CartVM>();
            }

            bool hasTicketInShopping = shopping.Cart.Any(m => m.TeamId == teamID);
            IEnumerable<Membership> membershipsOfUser = await _membershipService.GetAllMembershipsByUserIdAsync(User.FindFirstValue(ClaimTypes.NameIdentifier));
            bool hasMembershipFromTeam = membershipsOfUser.Any(t => t.Team.Id == teamID);


            if (team != null && !hasMembershipFromTeam && !hasTicketInShopping)
            {

                CartVM item = new CartVM
                {
                    Naam = team.Name,
                    Aantal = 1,
                    Prijs = 300,
                    TeamId = teamID,
                    Section = section, // zullen mogelijk geven om dit aan te passen
                    Ring = ring, // zullen mogelijk geven om dit aan te passen
                    DateCreated = DateTime.Now, // datum van match voor controle, geen nut om datum bij te houden van creatie ticket
                };

                shopping?.Cart?.Add(item);
                HttpContext.Session.SetObject("ShoppingCart", shopping);
            }
            else
            {
                return RedirectToAction("DuplicateAbonnement");
            }

            return RedirectToAction("Index", "ShoppingCart");
        }

        public IActionResult DuplicateAbonnement()
        {
            return View("DuplicateAbonnement");
        }


    }
}

FullstackOpdracht/Views/Shared/_LangLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FullstackOpdracht</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FullstackOpdracht.styles.css" asp-append-version="true" />
    <style>
        .bg-secondary {
            background-color: purple !important;
        }
    </style>
</head>
<body class="background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Profliga" asp-action="Index">Pro League</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Stadion" asp-action="Index">Stadions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Profliga" asp-action="Kalender">Kalender</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Profliga" asp-action="Tickets">Tickets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Subscription" asp-action="Index">Abonnementen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index"><img src="~/images/shoppingbag.jpg" /></a>
                        </li>
                    </ul>
                    @await Html.PartialAsync("_SelectCulture")
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container card">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2024 - Tickets Profliga
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        console.log("ok");
        $(document).ready(() => {
            $(".setLang").on("change", () => {
                $("#selectLanguage").submit();
            })
        })
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FullstackOpdracht/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FullstackOpdracht</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FullstackOpdracht.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
    <style>
        .trash{
            height: 50px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Profliga" asp-action="Index">Pro League</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Stadion" asp-action="Index">Stadions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Profliga" asp-action="Kalender">Kalender</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Profliga" asp-action="Tickets">Tickets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Subscription" asp-action="Index">Abonnementen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index"><img src="~/images/shoppingbag.jpg"/></a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2024 - Tickets Profliga 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FullstackOpdracht/Views/Shared/_SelectCulture.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> locOptions

@{
    // Represents the feature that provides the current request's culture information. (zie cookie culture wordt uitgelezen als deze aanwwezig) is)
    var currentRequestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = locOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var responseUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" :
        $"~{Context.Request.Path.Value}";
}

<div>
    <form id="selectLanguage" asp-controller="Profliga"
          asp-action="SetAppLanguage" asp-route-returnUrl="@responseUrl"
          method="post" class="form-horizontal" role="form">
        <label asp-for="@currentRequestCulture.RequestCulture.UICulture.Name">
            @Localizer["Select Language"]
        </label>
        <select name="lang" class="setLang"
                asp-for="@currentRequestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems">
        </select>
    </form>
</div>